version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "/docker-hub-creds:password"
    DOCKERHUB_USERNAME: "/docker-hub-creds:username"
phases:
pre_build:
commands:
- echo Logging in to Amazon docker registry..
- REPOSITORY_URI=docker.io/ajitcherian/dotnet-api-core-main
- COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
- IMAGE_TAG=${COMMIT_HASH:=latest}
build:
commands:
- echo Build started on `date`
- echo Building the Docker image...
- docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
- docker build -t $REPOSITORY_URI:latest .
- docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
post_build:
commands:
- echo Build completed on `date`
- echo Pushing the Docker images...
- docker push $REPOSITORY_URI:latest
- docker push $REPOSITORY_URI:$IMAGE_TAG
