version: 0.2
env:
  secrets-manager:
    #DOCKERHUB_PASS: docker-hub-creds
    #DOCKERHUB_USERNAME: "/
    DOCKERHUM: "docker-hub-creds"
phases:
  install:
    commands:
      - DOCKERHUB_USERNAME=$(echo $DOCKERHUM | jq -r '.username')
      - DOCKERHUB_PASS=$(echo $DOCKERHUM | jq -r '.password')
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - REPOSITORY_URI=ajitcherian/dotnet-api-core-main
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
